### ISSUE TITLE
Dashboard.Refresh badly mapped to boolean instead of string

### ISSUE THREAD

**Issue by cmunger** [adejoux/grafanaclient#1]
Hello,

First thanks for this great tool.
When playing with it it seems that with grafana 4.2.0 the field Dashboard.Refresh is badly mapped to a boolean value https://github.com/adejoux/grafanaclient/blob/master/api.go#L165 instead of a string to specify for example refresh every 5 seconds ("5s"). When using the boolean value (dashboard.Refresh = true) the dashboard dynamically generated crashes with error "TypeError: a.match is not a function
true"

Thanks

**Comment by adejoux** [comment]
Hello,

Thanks. I will fix it.

Alain

**Comment by cmunger** [comment]
Planning to release this fix ?

**Comment by adejoux** [comment]
Hello,

It's pushed on git. Are you meaning in nmon2influxdb ? If so, yes I will release a new version today or tomorrow.

Regards,

Alain
